# Generated by Django 2.0.9 on 2019-04-08 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_coresettingsmodel_root'),
    ]

    operations = [
        migrations.CreateModel(
            name='JustificationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=20, verbose_name='Nom court de la justification')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la justification')),
                ('date_just_start', models.DateField(verbose_name='Date de début de la justification')),
                ('date_just_end', models.DateField(verbose_name='Date de fin de la justification')),
                ('half_day_start', models.PositiveSmallIntegerField(default=0, verbose_name='Début demi-jour de la justification')),
                ('half_day_end', models.PositiveSmallIntegerField(default=1, verbose_name='Fin de demi-jour de la justification')),
                ('half_days', models.PositiveIntegerField(default=0, verbose_name='Nombre de demi-jour')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.StudentModel')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAbsenceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_absence', models.DateField(verbose_name="Date de l'absence")),
                ('morning', models.BooleanField(default=False, verbose_name='Matin')),
                ('afternoon', models.BooleanField(default=False, verbose_name='Après-midi')),
                ('username', models.CharField(max_length=100, verbose_name="Utilisateur qui a créé l'absence")),
                ('datetime_creation', models.DateTimeField(auto_now_add=True, verbose_name="Date et heure de création de l'absence")),
                ('datetime_update', models.DateTimeField(auto_now=True, verbose_name="Date et heure de mise à jour de l'absence")),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.StudentModel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAbsenceSettingsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_with_proeco', models.BooleanField(default=False, verbose_name='Synchronise les absences avec ProEco')),
                ('teachings', models.ManyToManyField(default=None, to='core.TeachingModel')),
            ],
        ),
    ]
