# Generated by Django 2.2.4 on 2019-10-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_absence', '0002_classenotemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentabsencesettingsmodel',
            name='filter_students_for_educ',
            field=models.CharField(choices=[('none', 'No filter'), ('year', 'Filter by year'), ('class', 'Filter by class')], default='none', max_length=5),
        ),
    ]
