# Generated by Django 3.2.11 on 2022-05-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student_absence", "0006_auto_20200108_1031"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentabsencemodel",
            name="is_processed",
            field=models.BooleanField(default=False),
        ),
    ]
