# Generated by Django 4.2 on 2024-02-22 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student_absence", "0008_periodmodel_day_of_week"),
    ]

    operations = [
        migrations.DeleteModel(
            name="JustificationModel",
        ),
    ]
