# Generated by Django 4.2 on 2024-04-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_absence", "0009_delete_justificationmodel"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="studentabsencemodel",
            index=models.Index(
                fields=["-date_absence", "student", "is_absent"],
                name="student_abs_date_ab_55fa3f_idx",
            ),
        ),
    ]
