# Generated by Django 2.2.3 on 2019-09-09 12:27
from datetime import timedelta

from django.db import migrations


def datetime_to_date(apps, schema_editor):
    Absence = apps.get_model("absence_prof", "Absence")
    for a in Absence.objects.all():
        a.date_absence_start = (a.datetime_absence_start + timedelta(hours=3)).date()
        a.date_absence_end = (a.datetime_absence_end - timedelta(hours=3)).date()
        a.save()


class Migration(migrations.Migration):
    dependencies = [
        ("absence_prof", "0004_auto_20190909_1427"),
    ]

    operations = [
        migrations.RunPython(datetime_to_date),
    ]
