# Generated by Django 5.2.7 on 2025-10-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail_notification", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="otheremailgroupmodel",
            name="pinned",
            field=models.BooleanField(default=False),
        ),
    ]
