# Generated by Django 5.2.8 on 2025-12-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail_notification", "0002_otheremailgroupmodel_pinned"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailnotificationsettingsmodel",
            name="replace_sender_domain_by",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Replace the domain for from email field.",
                max_length=100,
            ),
        ),
    ]
