# Generated by Django 2.2.11 on 2020-05-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0002_annuairesettingsmodel_show_credentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annuairesettingsmodel',
            name='show_credentials',
            field=models.BooleanField(default=True, help_text="Permet d'afficher/cacher les champs utilisateur/mot de passe dans la fiche info\n            et ainsi que la liste des mots de passe des élèves par classe"),
        ),
    ]
