# Generated by Django 2.2.22 on 2021-05-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("annuaire", "0004_annuairesettingsmodel_can_see_student_sensitive"),
    ]

    operations = [
        migrations.AddField(
            model_name="annuairesettingsmodel",
            name="show_schedule",
            field=models.BooleanField(default=True, help_text="Affiche l'horaire des cours."),
        ),
    ]
