# Generated by Django 4.2 on 2023-11-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("annuaire", "0005_annuairesettingsmodel_show_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="annuairesettingsmodel",
            name="can_see_inactives",
            field=models.ManyToManyField(
                blank=True, default=None, related_name="can_see_inactives", to="auth.group"
            ),
        ),
    ]
