# Generated by Django 4.2.15 on 2024-10-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("annuaire", "0006_annuairesettingsmodel_can_see_inactives"),
    ]

    operations = [
        migrations.AddField(
            model_name="annuairesettingsmodel",
            name="can_see_summary",
            field=models.ManyToManyField(
                blank=True, default=None, related_name="can_see_summary", to="auth.group"
            ),
        ),
    ]
