# Generated by Django 2.0.9 on 2019-01-07 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClasseModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("year", models.IntegerField()),
                ("letter", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="CoreSettingsModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "root",
                    models.URLField(
                        blank=True,
                        default=None,
                        help_text="URL vers le serveur HappySchool principal",
                        null=True,
                        verbose_name="Root URL",
                    ),
                ),
                (
                    "remote",
                    models.URLField(
                        blank=True,
                        default=None,
                        help_text="URL vers un serveur HappySchool distant",
                        null=True,
                        verbose_name="Remote URL",
                    ),
                ),
                (
                    "remote_token",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="Token généré sur le serveur distant",
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmailModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("display", models.CharField(default="", max_length=300)),
                ("is_pms", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ResponsibleModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("matricule", models.BigIntegerField(blank=True, null=True, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("email_school", models.EmailField(blank=True, max_length=254, null=True)),
                ("is_teacher", models.BooleanField(default=False)),
                ("is_educator", models.BooleanField(default=False)),
                ("is_secretary", models.BooleanField(default=False)),
                ("inactive_from", models.DateTimeField(blank=True, default=None, null=True)),
                ("classe", models.ManyToManyField(blank=True, default=None, to="core.ClasseModel")),
            ],
        ),
        migrations.CreateModel(
            name="StudentModel",
            fields=[
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                (
                    "matricule",
                    models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("inactive_from", models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TeachingModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("display_name", models.CharField(max_length=100)),
                (
                    "name",
                    models.CharField(help_text="Nom simple pour la programmation.", max_length=100),
                ),
            ],
        ),
        migrations.CreateModel(
            name="YearModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("year", models.IntegerField(verbose_name="year")),
            ],
        ),
        migrations.CreateModel(
            name="AdditionalStudentInfo",
            fields=[
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="core.StudentModel",
                    ),
                ),
                ("gender", models.CharField(blank=True, max_length=10)),
                ("scholar_year", models.CharField(blank=True, max_length=9)),
                ("previous_classe", models.CharField(blank=True, max_length=20)),
                ("orientation", models.CharField(blank=True, max_length=200)),
                ("birth_date", models.DateField(blank=True, null=True, verbose_name="birth date")),
                ("street", models.CharField(blank=True, max_length=500)),
                ("postal_code", models.CharField(blank=True, max_length=50)),
                ("locality", models.CharField(blank=True, max_length=200)),
                ("student_phone", models.CharField(blank=True, max_length=100)),
                ("student_mobile", models.CharField(blank=True, max_length=100)),
                ("student_email", models.EmailField(blank=True, max_length=254, null=True)),
                ("resp_last_name", models.CharField(blank=True, max_length=200)),
                ("resp_first_name", models.CharField(blank=True, max_length=200)),
                ("resp_phone", models.CharField(blank=True, max_length=100)),
                ("resp_mobile", models.CharField(blank=True, max_length=100)),
                ("resp_email", models.EmailField(blank=True, max_length=254, null=True)),
                ("father_last_name", models.CharField(blank=True, max_length=200)),
                ("father_first_name", models.CharField(blank=True, max_length=200)),
                ("father_job", models.CharField(blank=True, max_length=500)),
                ("father_phone", models.CharField(blank=True, max_length=100)),
                ("father_mobile", models.CharField(blank=True, max_length=100)),
                ("father_email", models.EmailField(blank=True, max_length=254, null=True)),
                ("mother_last_name", models.CharField(blank=True, max_length=200)),
                ("mother_first_name", models.CharField(blank=True, max_length=200)),
                ("mother_job", models.CharField(blank=True, max_length=500)),
                ("mother_phone", models.CharField(blank=True, max_length=100)),
                ("mother_mobile", models.CharField(blank=True, max_length=100)),
                ("mother_email", models.EmailField(blank=True, max_length=254, null=True)),
                ("doctor", models.CharField(blank=True, max_length=200)),
                ("doctor_phone", models.CharField(blank=True, max_length=200)),
                ("mutual", models.CharField(blank=True, max_length=200)),
                ("mutual_number", models.CharField(blank=True, max_length=200)),
                ("medical_information", models.CharField(blank=True, max_length=500)),
                ("username", models.CharField(blank=True, max_length=20)),
                ("password", models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name="studentmodel",
            name="classe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.ClasseModel",
            ),
        ),
        migrations.AddField(
            model_name="studentmodel",
            name="teaching",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.TeachingModel"
            ),
        ),
        migrations.AddField(
            model_name="studentmodel",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="responsiblemodel",
            name="teaching",
            field=models.ManyToManyField(blank=True, to="core.TeachingModel"),
        ),
        migrations.AddField(
            model_name="responsiblemodel",
            name="tenure",
            field=models.ManyToManyField(
                blank=True, default=None, related_name="tenure_classe", to="core.ClasseModel"
            ),
        ),
        migrations.AddField(
            model_name="responsiblemodel",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="emailmodel",
            name="teaching",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.TeachingModel",
            ),
        ),
        migrations.AddField(
            model_name="emailmodel",
            name="years",
            field=models.ManyToManyField(blank=True, to="core.YearModel"),
        ),
        migrations.AddField(
            model_name="classemodel",
            name="teaching",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.TeachingModel"
            ),
        ),
    ]
