# Generated by Django 2.2.3 on 2019-09-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_responsiblemodel_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalstudentinfo',
            name='password',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
