# Generated by Django 2.2.4 on 2019-09-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190901_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalstudentinfo',
            name='password',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
