# Generated by Django 2.2.13 on 2021-01-05 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20201209_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodCoreModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('name', models.CharField(max_length=200)),
                ('teaching', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TeachingModel')),
            ],
        ),
        migrations.CreateModel(
            name='CourseScheduleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField()),
                ('given_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.GivenCourseModel')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PeriodCoreModel')),
            ],
        ),
    ]
