# Generated by Django 2.2.22 on 2021-05-18 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_menuentrymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('teaching', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TeachingModel')),
            ],
        ),
        migrations.CreateModel(
            name='GroupLevelModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('levels', models.ManyToManyField(to='core.LevelModel')),
            ],
        ),
    ]
