# Generated by Django 3.2.11 on 2022-01-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_menuentrymodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="responsiblemodel",
            name="is_sync",
            field=models.BooleanField(default=True),
        ),
    ]
