# Generated by Django 3.2.11 on 2022-01-31 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_responsiblemodel_is_sync"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseschedulemodel",
            name="course_name",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddField(
            model_name="courseschedulemodel",
            name="is_sync",
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name="courseschedulemodel",
            name="given_course",
        ),
        migrations.AddField(
            model_name="courseschedulemodel",
            name="given_course",
            field=models.ManyToManyField(blank=True, default=None, to="core.GivenCourseModel"),
        ),
    ]
