# Generated by Django 2.2.22 on 2021-05-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_grouplevelmodel_levelmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsiblemodel',
            name='level',
            field=models.ManyToManyField(blank=True, default=None, to='core.LevelModel'),
        ),
    ]
