# Generated by Django 2.2.22 on 2021-05-27 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_responsiblemodel_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='classemodel',
            name='level',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.LevelModel'),
        ),
    ]
