# Generated by Django 3.2.11 on 2022-05-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_courseschedulemodel_place"),
    ]

    operations = [
        migrations.AddField(
            model_name="additionalstudentinfo",
            name="group",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
