# Generated by Django 3.2.11 on 2022-05-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_additionalstudentinfo_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="coresettingsmodel",
            name="day_scholar_year_start",
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name="coresettingsmodel",
            name="month_scholar_year_start",
            field=models.PositiveSmallIntegerField(default=8),
        ),
    ]
