# Generated by Django 4.2.16 on 2025-01-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_auto_20220524_1007"),
    ]

    operations = [
        migrations.CreateModel(
            name="ColumnToFieldImportModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "model",
                    models.CharField(
                        choices=[("ST", "Student"), ("RE", "Responsible")], max_length=2
                    ),
                ),
                ("column_to_field", models.JSONField()),
            ],
        ),
    ]
