# Generated by Django 4.2.16 on 2025-02-17 10:56

from django.db import migrations
from django.contrib.postgres.operations import BtreeGinExtension, UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_columntofieldimportmodel"),
    ]

    operations = [
        UnaccentExtension(),
        BtreeGinExtension(),
        migrations.RunSQL("CREATE TEXT SEARCH CONFIGURATION fr_unaccent ( COPY = french );"),
        migrations.RunSQL(
            "ALTER TEXT SEARCH CONFIGURATION fr_unaccent ALTER MAPPING FOR hword, hword_part, word WITH unaccent, french_stem;"
        ),
    ]
