# Generated by Django 5.2.1 on 2025-06-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_responsiblemodel_search_vector_resp_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coresettingsmodel",
            name="school_it_support_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
    ]
