# Generated by Django 5.2.3 on 2025-06-12 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_coresettingsmodel_school_it_support_email"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationLogModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("application", models.CharField(max_length=100)),
                ("related_view", models.CharField(default="", max_length=100)),
                ("related_object", models.IntegerField(blank=True, null=True)),
                ("datetime_creation", models.DateTimeField(auto_now_add=True)),
                ("message", models.TextField(blank=True)),
                ("recipients", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PR", "Processing"),
                            ("DO", "Sent"),
                            ("ER", "Error"),
                            ("WA", "Waiting"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.studentmodel"
                    ),
                ),
            ],
        ),
    ]
