# Generated by Django 5.2.3 on 2025-07-02 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_contactmodel_parentsettingmodel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentrelativemodel",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.contactmodel",
            ),
        ),
    ]
