# Generated by Django 5.2.3 on 2025-09-01 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_alter_studentrelativemodel_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="parentnotificationsettingsmodel",
            name="student",
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to="core.studentmodel"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="parentnotificationsettingsmodel",
            name="period",
            field=models.PositiveSmallIntegerField(
                default=7, verbose_name="Number of days between notifications"
            ),
        ),
    ]
