# Generated by Django 5.2.3 on 2025-09-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_parentnotificationsettingsmodel_student_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parentnotificationsettingsmodel",
            name="contact",
            field=models.EmailField(max_length=254),
        ),
    ]
