# Generated by Django 5.2.3 on 2025-09-04 09:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_alter_parentnotificationsettingsmodel_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentmodel",
            name="uuid",
            field=models.UUIDField(default=None, null=True),
        ),
    ]
