# Generated by Django 5.2.3 on 2025-09-04 09:25

import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):
    StudentModel = apps.get_model("core", "StudentModel")
    for row in StudentModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_studentmodel_uuid"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
