# Generated by Django 5.2.3 on 2025-09-04 09:25

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_auto_20250904_1125"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentmodel",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
