# Generated by Django 2.2.4 on 2019-08-22 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_absence_teacher', '0002_studentabsenceteachersettingsmodel_can_see_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentabsenceteachermodel',
            old_name='date',
            new_name='date_absence',
        ),
        migrations.RenameField(
            model_name='studentlatenessteachermodel',
            old_name='date',
            new_name='date_lateness',
        ),
    ]
