# Generated by Django 2.2.4 on 2019-08-30 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_absence_teacher', '0003_auto_20190822_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonmodel',
            name='classe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ClasseModel'),
        ),
    ]
