# Generated by Django 2.2.13 on 2020-08-19 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200818_1441'),
        ('student_absence_teacher', '0005_auto_20200819_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentlatenessteachermodel',
            name='lesson',
        ),
        migrations.AddField(
            model_name='studentlatenessteachermodel',
            name='given_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.GivenCourseModel'),
        ),
    ]
