# Generated by Django 2.2.13 on 2020-09-18 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("student_absence_teacher", "0006_auto_20200819_1544"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentabsenceteachermodel",
            name="status",
            field=models.CharField(
                choices=[("presence", "Présence"), ("lateness", "Retard"), ("absence", "Absence")],
                default="presence",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="studentabsenceteachersettingsmodel",
            name="select_student_by",
            field=models.CharField(
                choices=[("CL", "Par classe"), ("GC", "Par cours")], default="CL", max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="studentabsenceteachermodel",
            name="given_course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.GivenCourseModel",
            ),
        ),
    ]
