# Generated by Django 2.2.24 on 2021-08-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_absence_teacher', '0008_auto_20210819_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentabsenceteachersettingsmodel',
            name='select_student_by',
            field=models.CharField(choices=[('CL', 'Par classe'), ('GC', 'Par cours'), ('CLGC', 'Par classe et par cours')], default='CL', max_length=4),
        ),
    ]
