# Generated by Django 4.0.5 on 2022-11-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_absence_teacher', '0011_studentabsenceteachersettingsmodel_can_see_adding'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodmodel',
            name='day_of_week',
            field=models.CharField(default='1-5', max_length=10),
        ),
    ]
