# Generated by Django 4.2 on 2024-02-22 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("student_absence", "0009_delete_justificationmodel"),
        ("core", "0019_auto_20220524_1007"),
        ("student_absence_teacher", "0012_periodmodel_day_of_week"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentabsenceteachermodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("presence", "Présence"),
                    ("lateness", "Retard"),
                    ("absence", "Absence"),
                    ("excluded", "Exclus"),
                    ("exempted", "Dispensé"),
                    ("internship", "Stage"),
                ],
                default="presence",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="JustificationModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("short_name", models.CharField(max_length=20, verbose_name="Short name")),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("comment", models.TextField(blank=True, verbose_name="Comment")),
                ("date_just_start", models.DateField(verbose_name="Start date")),
                ("date_just_end", models.DateField(verbose_name="End date")),
                (
                    "half_day_start",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Half day start (morning or afternoon)"
                    ),
                ),
                (
                    "half_day_end",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Half day end (morning or afternoon)"
                    ),
                ),
                (
                    "half_days",
                    models.PositiveIntegerField(default=1, verbose_name="Half days count"),
                ),
                (
                    "absences",
                    models.ManyToManyField(blank=True, to="student_absence.studentabsencemodel"),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.studentmodel"
                    ),
                ),
            ],
        ),
    ]
