# Generated by Django 4.2 on 2024-04-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_absence_teacher", "0013_alter_studentabsenceteachermodel_status_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="studentabsenceteachermodel",
            index=models.Index(
                fields=["-date_absence", "student", "status"], name="student_abs_date_ab_2ace35_idx"
            ),
        ),
    ]
