# Generated by Django 4.2 on 2024-04-25 13:02

from django.conf import settings
from django.db import migrations, models

if "student_absence" in settings.INSTALLED_APPS:

    class Migration(migrations.Migration):

        dependencies = [
            ("student_absence_teacher", "0015_periodeducmodel_and_more"),
        ]

        operations = [
            migrations.AlterField(
                model_name="justificationmodel",
                name="absences",
                field=models.ManyToManyField(
                    blank=True, to="student_absence_teacher.studentabsenceeducmodel"
                ),
            ),
        ]

else:

    class Migration(migrations.Migration):

        dependencies = [
            ("student_absence_teacher", "0015_periodeducmodel_and_more"),
        ]

        operations = [
            migrations.AddField(
                model_name="justificationmodel",
                name="absences",
                field=models.ManyToManyField(
                    blank=True, to="student_absence_teacher.studentabsenceeducmodel"
                ),
            ),
        ]
