# Generated by Django 4.2 on 2024-06-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_absence_teacher', '0017_justmotivemodel_alter_periodeducmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='justmotivemodel',
            name='accepted',
            field=models.BooleanField(default=True),
        ),
    ]
