# Generated by Django 4.2 on 2024-06-20 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_absence_teacher', '0018_justmotivemodel_accepted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='justmotivemodel',
            old_name='accepted',
            new_name='admissible',
        ),
    ]
