# Generated by Django 4.2 on 2024-06-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_absence_teacher', '0019_rename_accepted_justmotivemodel_admissible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='justmotivemodel',
            name='admissible',
        ),
        migrations.AddField(
            model_name='justmotivemodel',
            name='admissible_up_to',
            field=models.PositiveSmallIntegerField(default=1000),
        ),
    ]
