# Generated by Django 4.2 on 2024-06-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_absence_teacher', '0020_remove_justmotivemodel_admissible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentabsenceeducmodel',
            name='student_responsible_warned',
            field=models.BooleanField(default=False),
        ),
    ]
