# Generated by Django 4.2 on 2024-06-27 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_absence_teacher', '0021_studentabsenceeducmodel_student_responsible_warned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentabsenceeducmodel',
            old_name='student_responsible_warned',
            new_name='mail_warning',
        ),
    ]
