# Generated by Django 4.2.15 on 2024-08-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('student_absence_teacher', '0023_mailtemplatemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentabsenceteachersettingsmodel',
            name='can_see_exclusion',
            field=models.ManyToManyField(blank=True, default=None, related_name='can_see_exclusion', to='auth.group'),
        ),
    ]
