# Generated by Django 4.2.20 on 2025-05-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_absence_teacher", "0025_mailtriggermodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailtriggermodel",
            name="mail_content",
            field=models.TextField(default=""),
        ),
    ]
