# Generated by Django 5.2.9 on 2026-05-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_absence_teacher", "0026_mailtriggermodel_mail_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentabsenceteachersettingsmodel",
            name="sender_email",
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
