# Generated by Django 2.0.9 on 2019-05-16 08:59

from django.core.exceptions import ObjectDoesNotExist
from django.db import migrations, models
import django.db.models.deletion


def migrate_change(apps, schema_editor):
    ScheduleChangeModel = apps.get_model('schedule_change', 'ScheduleChangeModel')
    ScheduleChangeTypeModel = apps.get_model('schedule_change', 'ScheduleChangeTypeModel')

    for sc in ScheduleChangeModel.objects.all():
        try:
            ch = ScheduleChangeTypeModel.objects.get(name=sc.change_old)
            sc.change = ch
            sc.save()
        except ObjectDoesNotExist:
            ch = ScheduleChangeTypeModel.objects.create(name=sc.change_old)
            sc.change = ch
            sc.save()

class Migration(migrations.Migration):

    dependencies = [
        ('schedule_change', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleChangeCategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('color', models.CharField(help_text='Valeur hexadecimal de la couleur.', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleChangePlaceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleChangeTypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='schedulechangemodel',
            old_name='change',
            new_name='change_old',
        ),
        migrations.AddField(
            model_name='schedulechangemodel',
            name='change',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule_change.ScheduleChangeTypeModel'),
        ),
        migrations.RunPython(migrate_change),
        migrations.RemoveField(
            model_name='schedulechangemodel',
            name='change_old',
        ),
        migrations.AddField(
            model_name='schedulechangemodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule_change.ScheduleChangeCategoryModel'),
        ),
    ]
