# Generated by Django 2.2.3 on 2019-09-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appel',
            name='user',
            field=models.CharField(default='', max_length=100),
        ),
    ]
