# Generated by Django 2.2.11 on 2020-05-12 09:50

from django.db import migrations
from django.contrib.auth.models import Permission
from django.db.models import ObjectDoesNotExist


def remove_access_permission(apps, schema_editor):
    try:
        Permission.objects.get(codename="access_appel").delete()
    except ObjectDoesNotExist:
        # Old permission never existed, skipping.
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('appels', '0003_auto_20191025_1343'),
    ]

    operations = [
        migrations.RunPython(remove_access_permission),
        migrations.AlterModelOptions(
            name='appel',
            options={},
        ),
    ]
