# Generated by Django 2.2.11 on 2020-05-12 12:31

from django.db import migrations
from django.core.management import call_command


def load_fixtures(apps, schema_editor):
    MotiveModel = apps.get_model("appels", "MotiveModel")
    ObjectModel = apps.get_model("appels", "ObjectModel")

    if MotiveModel.objects.count() == 0:
        call_command("loaddata", "appels_motives", app_label="appels")

    if ObjectModel.objects.count() == 0:
        call_command("loaddata", "appels_objects", app_label="appels")


class Migration(migrations.Migration):

    dependencies = [
        ('appels', '0004_auto_20200512_1150'),
    ]

    operations = [
        migrations.RunPython(load_fixtures),
    ]
