# Generated by Django 4.0.8 on 2023-05-01 14:42

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('infirmerie', '0002_auto_20200420_1154'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='passage',
            constraint=models.CheckConstraint(check=models.Q(('datetime_sortie__isnull', True), ('datetime_sortie__gte', django.db.models.expressions.F('datetime_arrive')), _connector='OR'), name='correct_datetime'),
        ),
    ]
