# Generated by Django 2.2.3 on 2019-09-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dossier_eleve", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caseleve",
            name="demandeur",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="caseleve",
            name="user",
            field=models.CharField(default="", max_length=100),
        ),
    ]
