# Generated by Django 2.2.3 on 2019-11-18 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dossier_eleve', '0003_dossierelevesettingsmodel_filter_teacher_entries_by_tenure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caseleve',
            options={'permissions': (('access_dossier_eleve', 'Can access to dossier_eleve data'), ('set_sanction', 'Can set sanction'), ('ask_sanction', 'Can ask sanction'))},
        ),
    ]
