# This file is part of HappySchool.
#
# HappySchool is the legal property of its developers, whose names
# can be found in the AUTHORS file distributed with this source
# distribution.
#
# HappySchool is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# HappySchool is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with HappySchool.  If not, see <http://www.gnu.org/licenses/>.

# Generated by Django 2.2.3 on 2019-11-18 08:36

from django.db import migrations
from django.db.models import ObjectDoesNotExist
from django.contrib.auth.models import Group, Permission


def migrate_set_sanctions(apps, schema_editor):
    try:
        can_set_permission = Permission.objects.get(codename="set_sanction")
        can_ask_permission = Permission.objects.get(codename="ask_sanction")
        for g in can_set_permission.group_set.all():
            g.permissions.add(can_ask_permission)
            g.save()
        for u in can_set_permission.user_set.all():
            u.user_permissions.add(can_ask_permission)
            u.save()
    except ObjectDoesNotExist:
        # Old permission never existed, skipping.
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('dossier_eleve', '0004_auto_20191118_0934'),
    ]

    operations = [
        migrations.RunPython(migrate_set_sanctions),
    ]
