# Generated by Django 2.2.8 on 2019-12-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dossier_eleve", "0005_auto_20191118_0936"),
    ]

    operations = [
        migrations.AddField(
            model_name="sanctiondecisiondisciplinaire",
            name="send_email_at_creation_to_responsible",
            field=models.BooleanField(
                default=False,
                help_text="Si activé, envoi automatiquement un email au responsable de l'élève à la création\n            d'un cas (pas d'une demande).",
            ),
        ),
        migrations.AlterField(
            model_name="dossierelevesettingsmodel",
            name="all_access",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                help_text="Permet à un membre du ou des groupes sélectionnés ayant accès qu'à\n        certains niveaux, d'avoir accès à tous les niveaux.\n        ",
                to="auth.Group",
            ),
        ),
        migrations.AlterField(
            model_name="dossierelevesettingsmodel",
            name="coord_allow_visibility_to",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                help_text="La liste des groupes qui seront affichés pour le choix de la visibilité\n        par un membre des coordonateurs. Ne concerne que les groupes 'direction', 'coordonateur',\n        'educateur', 'professeur' et 'pms'.",
                related_name="coord_allow_visibility_to",
                to="auth.Group",
            ),
        ),
        migrations.AlterField(
            model_name="dossierelevesettingsmodel",
            name="coord_force_visibility_to",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                help_text="Les groupes selectionés auront forcément la visibilité sur les cas venant\n        d'un coordonateur. Ne concerne que les groupes 'direction', 'coordonateur',\n        'educateur', 'professeur' et 'pms'.",
                related_name="coord_force_visibility_to",
                to="auth.Group",
            ),
        ),
        migrations.AlterField(
            model_name="dossierelevesettingsmodel",
            name="dir_allow_visibility_to",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                help_text="La liste des groupes qui seront affichés pour le choix de la visibilité\n        par un membre de la direction. Ne concerne que les groupes 'direction', 'coordonateur',\n        'educateur', 'professeur' et 'pms'.",
                related_name="dir_allow_visibility_to",
                to="auth.Group",
            ),
        ),
        migrations.AlterField(
            model_name="dossierelevesettingsmodel",
            name="dir_force_visibility_to",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                help_text="Les groupes selectionés auront forcément la visibilité sur les cas venant\n        de la direction. Ne concerne que les groupes 'direction', 'coordonateur',\n        'educateur', 'professeur' et 'pms'.",
                related_name="dir_force_visibility_to",
                to="auth.Group",
            ),
        ),
        migrations.AlterField(
            model_name="dossierelevesettingsmodel",
            name="educ_allow_visibility_to",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                help_text="La liste des groupes qui seront affichés pour le choix de la visibilité\n        par un membre des éducateurs. Ne concerne que les groupes 'direction', 'coordonateur',\n        'educateur', 'professeur' et 'pms'.",
                related_name="educ_allow_visibility_to",
                to="auth.Group",
            ),
        ),
        migrations.AlterField(
            model_name="dossierelevesettingsmodel",
            name="educ_force_visibility_to",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                help_text="Les groupes selectionés auront forcément la visibilité sur les cas venant\n        d'un éducateur. Ne concerne que les groupes 'direction', 'coordonateur',\n        'educateur', 'professeur' et 'pms'.",
                related_name="educ_force_visibility_to",
                to="auth.Group",
            ),
        ),
        migrations.AlterField(
            model_name="dossierelevesettingsmodel",
            name="pms_allow_visibility_to",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                help_text="La liste des groupes qui seront affichés pour le choix de la visibilité\n        par un membre du pms. Ne concerne que les groupes 'direction', 'coordonateur',\n        'educateur', 'professeur' et 'pms'.",
                related_name="pms_allow_visibility_to",
                to="auth.Group",
            ),
        ),
        migrations.AlterField(
            model_name="dossierelevesettingsmodel",
            name="pms_force_visibility_to",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                help_text="Les groupes selectionés auront forcément la visibilité sur les cas venant\n        du pms. Ne concerne que les groupes 'direction', 'coordonateur',\n        'educateur', 'professeur' et 'pms'.",
                related_name="pms_force_visibility_to",
                to="auth.Group",
            ),
        ),
        migrations.AlterField(
            model_name="dossierelevesettingsmodel",
            name="teacher_allow_visibility_to",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                help_text="La liste des groupes qui seront affichés pour le choix de la visibilité\n        par un membre des professeurs. Ne concerne que les groupes 'direction', 'coordonateur',\n        'educateur', 'professeur' et 'pms'.",
                related_name="teacher_allow_visibility_to",
                to="auth.Group",
            ),
        ),
        migrations.AlterField(
            model_name="dossierelevesettingsmodel",
            name="teacher_force_visibility_to",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                help_text="Les groupes selectionés auront forcément la visibilité sur les cas venant\n        d'un professeur. Ne concerne que les groupes 'direction', 'coordonateur',\n        'educateur', 'professeur' et 'pms'.",
                related_name="teacher_force_visibility_to",
                to="auth.Group",
            ),
        ),
    ]
