# Generated by Django 2.2.9 on 2020-01-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossier_eleve', '0006_auto_20191216_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifySanctionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(choices=[('PA', 'Parents'), ('LR', 'Responsable légal'), ('SR', "Responsable à l'école (éduc/coord)")], default='LR', max_length=2)),
                ('frequency', models.PositiveSmallIntegerField(default=5, help_text='Fréquence à laquelle la notification sera envoyé. Par exemple, une fréqunce de 5\n            enverra une notification tous les multiples de 5 (0 non inclus) : à la 5ème, 10ème,… sanctions.')),
            ],
        ),
        migrations.RemoveField(
            model_name='sanctiondecisiondisciplinaire',
            name='send_email_at_creation_to_responsible',
        ),
        migrations.AddField(
            model_name='sanctiondecisiondisciplinaire',
            name='notify',
            field=models.ManyToManyField(help_text="Permet d'envoyer une notification aux parents/responsable légal ou responsable de l'école\n            (éducateurs/coordonateur) à une fréquence particulière (tous les X fois).", to='dossier_eleve.NotifySanctionModel'),
        ),
    ]
