# Generated by Django 2.2.9 on 2020-01-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dossier_eleve", "0007_auto_20200118_1308"),
    ]

    operations = [
        migrations.AddField(
            model_name="dossierelevesettingsmodel",
            name="enable_disciplinary_council",
            field=models.BooleanField(
                default=True,
                help_text="Si activé avec la demande de sanction, permet de prévoir de manière facultative\n        une date pour statuer de la pertinence d'une demande de sanction.",
            ),
        ),
        migrations.AlterField(
            model_name="notifysanctionmodel",
            name="frequency",
            field=models.PositiveSmallIntegerField(
                default=5,
                help_text="Fréquence à laquelle la notification sera envoyé. Par exemple, une fréqunce de 5\n            enverra une notification tous les multiples de 5 : à la 5ème, 10ème,… sanctions.\n            Une fréquence de 1, enverra une notification à chaque nouvelle sanction.",
            ),
        ),
    ]
