# Generated by Django 2.2.11 on 2020-05-12 10:07

from django.db import migrations
from django.contrib.auth.models import Permission
from django.db.models import ObjectDoesNotExist


def migrate_access_permission(apps, schema_editor):
    try:
        old_permission = Permission.objects.get(codename="access_dossier_eleve")
        new_permission = Permission.objects.get(codename="view_caseleve")
        for g in old_permission.group_set.all():
            g.permissions.add(new_permission)
            g.save()
        for u in old_permission.user_set.all():
            u.user_permissions.add(new_permission)
            u.save()

        # Remove old permission
        old_permission.delete()
    except ObjectDoesNotExist:
        # Old permission never existed, skipping.
        pass


class Migration(migrations.Migration):
    dependencies = [
        ("dossier_eleve", "0008_auto_20200119_2111"),
    ]

    operations = [
        migrations.RunPython(migrate_access_permission),
        migrations.AlterModelOptions(
            name="caseleve",
            options={},
        ),
    ]
