# Generated by Django 2.2.11 on 2020-05-12 12:17

from django.db import migrations
from django.core.management import call_command


def load_fixtures(apps, schema_editor):
    InfoEleve = apps.get_model("dossier_eleve", "InfoEleve")
    SanctionDecisionDisciplinaire = apps.get_model("dossier_eleve", "SanctionDecisionDisciplinaire")

    if InfoEleve.objects.count() == 0:
        call_command("loaddata", "dossier_eleve_infos", app_label="dossier_eleve")

    if SanctionDecisionDisciplinaire.objects.count() == 0:
        call_command("loaddata", "dossier_eleve_sanctions", app_label="dossier_eleve")


class Migration(migrations.Migration):

    dependencies = [
        ('dossier_eleve', '0012_sanctiondecisiondisciplinaire_letter_comment'),
    ]

    operations = [
        migrations.RunPython(load_fixtures),
    ]
