# Generated by Django 2.2.19 on 2021-05-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0011_update_proxy_permissions"),
        ("dossier_eleve", "0014_auto_20201210_1043"),
    ]

    operations = [
        migrations.AddField(
            model_name="dossierelevesettingsmodel",
            name="tenure_allow_visibility_to",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                help_text="Les groupes selectionés auront forcément la visibilité sur les cas venant\n        des titulaires. Ne concerne que les groupes 'direction', 'coordonateur',\n        'educateur', 'professeur' et 'pms'.",
                related_name="tenure_allow_visibility_to",
                to="auth.Group",
            ),
        ),
        migrations.AddField(
            model_name="dossierelevesettingsmodel",
            name="tenure_force_visibility_to",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                help_text="Les groupes selectionés auront forcément la visibilité sur les cas venant\n        des titulaires. Ne concerne que les groupes 'direction', 'coordonateur',\n        'educateur', 'professeur' et 'pms'.",
                related_name="tenure_force_visibility_to",
                to="auth.Group",
            ),
        ),
        migrations.AlterField(
            model_name="dossierelevesettingsmodel",
            name="filter_teacher_entries_by_tenure",
            field=models.BooleanField(default=True, help_text="Déprécié. N'est plus utilisé."),
        ),
    ]
