# Generated by Django 2.2.22 on 2021-06-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossier_eleve', '0017_auto_20210531_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossierelevesettingsmodel',
            name='filter_teacher_entries_by_tenure',
            field=models.BooleanField(default=True, help_text='Déprécié.'),
        ),
    ]
