# Generated by Django 3.2.9 on 2021-12-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossier_eleve', '0022_auto_20211126_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseleve',
            name='sanction_faite',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
