# Generated by Django 3.2.11 on 2022-02-16 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dossier_eleve', '0023_alter_caseleve_sanction_faite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caseleve',
            old_name='matricule',
            new_name='student',
        ),
    ]
