# Generated by Django 4.0.5 on 2023-03-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossier_eleve', '0025_dossierelevesettingsmodel_export_retenues_own_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseleve',
            name='explication_commentaire',
            field=models.TextField(),
        ),
    ]
