# Generated by Django 4.2.15 on 2024-11-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dossier_eleve", "0026_alter_caseleve_explication_commentaire"),
    ]

    operations = [
        migrations.AddField(
            model_name="caseleve",
            name="date_sanction_end",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de fin de la sanction"
            ),
        ),
    ]
