# Generated by Django 5.2.3 on 2025-06-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dossier_eleve", "0027_caseleve_date_sanction_end"),
    ]

    operations = [
        migrations.CreateModel(
            name="InfoStatisticsModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("display", models.CharField(max_length=100)),
                ("info", models.ManyToManyField(to="dossier_eleve.infoeleve")),
            ],
        ),
    ]
