# Generated by Django 5.2.9 on 2026-01-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dossier_eleve", "0028_infostatisticsmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupCaseModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("datetime_creation", models.DateTimeField(auto_now_add=True)),
                ("datetime_update", models.DateTimeField(auto_now=True)),
                ("cases", models.ManyToManyField(to="dossier_eleve.caseleve")),
            ],
        ),
    ]
