# Generated by Django 2.2.8 on 2019-12-09 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pia', '0005_branchstatementmodel_classcouncilpiamodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disorderresponsemodel',
            name='disorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pia.DisorderModel'),
        ),
    ]
