# Generated by Django 2.2.8 on 2020-03-02 11:00

from django.db import migrations, models
import django.db.models.deletion


def move_data(apps, schema_editor):
    BranchGoalModel = apps.get_model("pia", "BranchGoalModel")
    BranchGoalItemModel = apps.get_model("pia", "BranchGoalItemModel")

    for bg in BranchGoalModel.objects.all():
        BranchGoalItemModel.objects.create(id=bg.id, goal=bg.goal, branch=bg.branch)

    CrossGoalModel = apps.get_model("pia", "CrossGoalModel")
    CrossGoalItemModel = apps.get_model("pia", "CrossGoalItemModel")
    for cg in CrossGoalModel.objects.all():
        newItem = CrossGoalItemModel(id=cg.id, goal=cg.goal)
        newItem.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_auto_20200119_2055"),
        ("pia", "0008_auto_20191216_1340"),
    ]

    operations = [
        migrations.CreateModel(
            name="BranchGoalItemModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("goal", models.CharField(max_length=200)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pia.BranchModel"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CrossGoalItemModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("goal", models.CharField(max_length=200)),
                ("teachings", models.ManyToManyField(to="core.TeachingModel")),
            ],
        ),
        migrations.RunPython(move_data),
        migrations.RemoveField(
            model_name="crossgoalmodel",
            name="teachings",
        ),
        migrations.DeleteModel(
            name="BranchGoalModel",
        ),
        migrations.DeleteModel(
            name="CrossGoalModel",
        ),
    ]
