# Generated by Django 2.2.8 on 2020-03-02 11:18

from django.db import migrations


def move_data(apps, schema_editor):
    GoalModel = apps.get_model("pia", "GoalModel")
    CrossGoalModel = apps.get_model("pia", "CrossGoalModel")
    SubGoalModel = apps.get_model("pia", "SubGoalModel")
    BranchGoalModel = apps.get_model("pia", "BranchGoalModel")
    for gm in GoalModel.objects.all():
        cgm = CrossGoalModel.objects.create(
            id=gm.id,
            pia_model=gm.pia_model,
            date_start=gm.date_start,
            date_end=gm.date_end,
            indicator_action=gm.indicator_action,
            given_help=gm.given_help,
            self_assessment=gm.self_assessment,
            assessment=gm.assessment,
            datetime_creation=gm.datetime_creation,
            datetime_update=gm.datetime_update,
            cross_goals=gm.cross_goals
        )
        cgm.responsible.set(gm.responsible.all())
        cgm.save()

        for sgm in SubGoalModel.objects.filter(goal=gm):
            bgm = BranchGoalModel.objects.create(
                id=sgm.id,
                pia_model=gm.pia_model,
                date_start=gm.date_start,
                date_end=gm.date_end,
                indicator_action=gm.indicator_action,
                given_help=gm.given_help,
                self_assessment=gm.self_assessment,
                assessment=gm.assessment,
                datetime_creation=gm.datetime_creation,
                datetime_update=gm.datetime_update,
                branch=sgm.branch,
                branch_goals=sgm.branch_goals,
                parent_commitment=sgm.parent_commitment
            )
            bgm.responsible.set(gm.responsible.all())
            bgm.save()


class Migration(migrations.Migration):

    dependencies = [
        ('pia', '0010_branchgoalmodel_crossgoalmodel'),
    ]

    operations = [
        migrations.RunPython(move_data),
        migrations.RemoveField(
            model_name='subgoalmodel',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='subgoalmodel',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='subgoalmodel',
            name='goal',
        ),
        migrations.DeleteModel(
            name='GoalModel',
        ),
        migrations.DeleteModel(
            name='SubGoalModel',
        ),
    ]
