# Generated by Django 2.2.11 on 2020-03-20 15:13

from django.db import migrations, models
import django.db.models.deletion


def move_data(apps, schema_editor):
    BranchGoalModel = apps.get_model("pia", "BranchGoalModel")
    if BranchGoalModel.objects.all().count() == 0:
        return

    BranchModel = apps.get_model("pia", "BranchModel")
    for bg in BranchGoalModel.objects.filter(branch=None):
        bg.branch = BranchModel.objects.first()


class Migration(migrations.Migration):

    dependencies = [
        ('pia', '0013_piasettingsmodel_filter_teacher_entries_by_tenure'),
    ]

    operations = [
        migrations.RunPython(move_data),
        migrations.AlterField(
            model_name='branchgoalmodel',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pia.BranchModel'),
        ),
        migrations.AlterField(
            model_name='piasettingsmodel',
            name='filter_teacher_entries_by_tenure',
            field=models.BooleanField(default=False, help_text='\n        Si activé, seuls les titulaires peuvent voir les PIA de leurs élèves.\n        Sinon sera limité aux classes associées.\n        '),
        ),
    ]
