# Generated by Django 2.2.11 on 2020-05-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pia', '0015_auto_20200507_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='piamodel',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='pia.AttachmentModel'),
        ),
    ]
