# Generated by Django 2.2.8 on 2020-07-09 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pia', '0016_piamodel_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchgoalitemmodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pia.BranchModel'),
        ),
    ]
