# Generated by Django 2.2.13 on 2020-12-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0011_update_proxy_permissions"),
        ("pia", "0018_piamodel_other_adjustments"),
    ]

    operations = [
        migrations.AddField(
            model_name="piasettingsmodel",
            name="all_access",
            field=models.ManyToManyField(blank=True, default=None, to="auth.Group"),
        ),
        migrations.AlterField(
            model_name="piamodel",
            name="other_adjustments",
            field=models.TextField(blank=True),
        ),
    ]
