# Generated by Django 2.2.13 on 2020-12-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pia", "0019_auto_20201207_1409"),
    ]

    operations = [
        migrations.AddField(
            model_name="crossgoalmodel",
            name="branches",
            field=models.ManyToManyField(blank=True, to="pia.BranchModel"),
        ),
    ]
