# Generated by Django 3.2.9 on 2021-12-09 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pia", "0022_auto_20210202_1148"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceDifficultyModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("resource", models.CharField(max_length=300)),
                ("difficulty", models.CharField(max_length=300)),
                ("category", models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="StudentStateModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pia.branchmodel",
                    ),
                ),
                (
                    "class_council",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pia.classcouncilpiamodel"
                    ),
                ),
                (
                    "difficulties",
                    models.ManyToManyField(
                        blank=True, related_name="difficulties", to="pia.ResourceDifficultyModel"
                    ),
                ),
                (
                    "resources",
                    models.ManyToManyField(
                        blank=True, related_name="resources", to="pia.ResourceDifficultyModel"
                    ),
                ),
                (
                    "datetime_creation",
                    models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
                ),
                ("datetime_update", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name="BranchStatementModel",
            new_name="OtherStatementModel",
        ),
    ]
