# Generated by Django 3.2.9 on 2021-12-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pia', '0023_resourcedifficultymodel_studentstatemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogPIAModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(max_length=300)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='studentstatemodel',
            name='datetime_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
