# Generated by Django 4.0.5 on 2022-10-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pia', '0025_crossgoalitemmodel_advanced_crossgoalitemmodel_basic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchgoalitemmodel',
            name='advanced',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='branchgoalitemmodel',
            name='basic',
            field=models.BooleanField(default=False),
        ),
    ]
