# Generated by Django 4.0.6 on 2023-01-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pia', '0026_branchgoalitemmodel_advanced_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisorderResponseCategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='disorderresponsemodel',
            name='categories',
            field=models.ManyToManyField(to='pia.disorderresponsecategorymodel'),
        ),
    ]
