# Generated by Django 4.0.8 on 2023-01-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pia', '0027_disorderresponsecategorymodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disorderresponsecategorymodel',
            name='explanation',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
