# Generated by Django 4.0.8 on 2023-01-19 13:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pia', '0028_disorderresponsecategorymodel_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='piamodel',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piamodel',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
