# Generated by Django 4.2 on 2023-06-22 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pia", "0030_selecteddisorderresponsemodel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisorderCareModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date_start", models.DateField()),
                ("date_end", models.DateField()),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("datetime_updated", models.DateTimeField(auto_now=True)),
                ("disorder", models.ManyToManyField(blank=True, to="pia.disordermodel")),
                (
                    "pia_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pia.piamodel"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SelectedDisorderResponseNewModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pia.disorderresponsecategorymodel",
                    ),
                ),
                (
                    "disorder_care",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pia.disordercaremodel"
                    ),
                ),
                (
                    "disorder_response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pia.disorderresponsemodel"
                    ),
                ),
            ],
        ),
    ]
