# Generated by Django 4.2 on 2023-06-22 13:27
from datetime import date

from django.db import migrations, models


def move_to_disorder_care(apps, schema_editor):
    PIAModel = apps.get_model("pia", "PIAModel")
    SelectedDisorderResponseNewModel = apps.get_model("pia", "SelectedDisorderResponseNewModel")
    DisorderCareModel = apps.get_model("pia", "DisorderCareModel")

    start_date = date(2022, 8, 28)
    end_date = date(2023, 7, 7)

    for pia in PIAModel.objects.all():
        disorder_care = DisorderCareModel(pia_model=pia, date_start=start_date, date_end=end_date)
        disorder_care.save()
        disorder_care.disorder.set(pia.disorder.all())
        for old_selected in pia.selected_disorder_response.all():
            new_selected = SelectedDisorderResponseNewModel(
                disorder_care=disorder_care,
                category=old_selected.category,
                disorder_response=old_selected.disorder_response,
            )
            new_selected.save()


class Migration(migrations.Migration):
    dependencies = [
        ("pia", "0031_disordercaremodel_selecteddisorderresponsenewmodel"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="disordercaremodel",
            constraint=models.CheckConstraint(
                check=models.Q(("date_start__lte", models.F("date_end"))),
                name="ensure_date_start_lte_date_end",
            ),
        ),
        migrations.RunPython(move_to_disorder_care),
    ]
