# Generated by Django 4.2 on 2023-09-04 19:23
from datetime import date

from django.db import migrations, models
import django.db.models.deletion


def move_to_new_schedule_adjustment(apps, schema_editor):
    PIAModel = apps.get_model("pia", "PIAModel")
    ScheduleAdjustmentPlanModel = apps.get_model("pia", "ScheduleAdjustmentPlanModel")

    start_date = date(2022, 8, 28)
    end_date = date(2023, 7, 7)

    for pia in PIAModel.objects.all():
        schedule_adjustements = pia.schedule_adjustment.all()
        if not schedule_adjustements.exists():
            continue

        plan = ScheduleAdjustmentPlanModel(
            pia_model=pia,
            date_start=start_date,
            date_end=end_date,
        )
        plan.save()
        plan.schedule_adjustment.set(schedule_adjustements)


class Migration(migrations.Migration):
    dependencies = [
        ("pia", "0032_disordercare_migration"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleAdjustmentPlanModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date_start", models.DateField()),
                ("date_end", models.DateField()),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("datetime_updated", models.DateTimeField(auto_now=True)),
                (
                    "pia_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pia.piamodel"
                    ),
                ),
                (
                    "schedule_adjustment",
                    models.ManyToManyField(blank=True, to="pia.scheduleadjustmentmodel"),
                ),
            ],
        ),
        migrations.RunPython(move_to_new_schedule_adjustment),
    ]
