# Generated by Django 4.2 on 2024-01-15 12:24

from django.db import migrations, models


def move_other_adjustments_inside(apps, schema_editor):
    PIAModel = apps.get_model("pia", "PIAModel")

    for pia in PIAModel.objects.filter(advanced=True):
        disorder_cares = pia.disordercaremodel_set.all().order_by("-date_start")
        if not disorder_cares.exists():
            continue

        other_adjustments = pia.otheradjustmentsmodel_set.all().order_by("-date_start")
        if not other_adjustments.exists():
            continue

        last_disorder_care = disorder_cares.first()
        last_other_adjustments = other_adjustments.first()
        last_disorder_care.other_adjustments = last_other_adjustments.other_adjustments
        last_disorder_care.save()


class Migration(migrations.Migration):
    dependencies = [
        ("pia", "0035_coursereinforcementmodel_activitysupportmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="disordercaremodel",
            name="other_adjustments",
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(move_other_adjustments_inside),
    ]
