# Generated by Django 4.2 on 2024-01-15 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pia", "0036_disordercaremodel_other_adjustments"),
    ]

    operations = [
        migrations.AddField(
            model_name="selecteddisorderresponsenewmodel",
            name="custom_response",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="selecteddisorderresponsenewmodel",
            name="disorder_response",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pia.disorderresponsemodel",
            ),
        ),
    ]
