# Generated by Django 4.2 on 2024-03-14 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pia", "0038_assessmentmodel_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntermediateEvaluationModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date_evaluation", models.DateField()),
                (
                    "branch_goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pia.branchgoalmodel"
                    ),
                ),
                (
                    "evaluation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pia.assessmentmodel"
                    ),
                ),
            ],
        ),
    ]
