# Generated by Django 5.2.7 on 2025-10-02 10:26

from django.db import migrations, models
from django.contrib.auth.models import Group
from django.conf import settings


def add_default_group(apps, schema_editor):
    AttachmentModel = apps.get_model("pia", "AttachmentModel")
    group_names = [
        settings.DIRECTION_GROUP,
        settings.TEACHER_GROUP,
        settings.EDUCATOR_GROUP,
        settings.COORDONATOR_GROUP,
    ]
    default_groups = Group.objects.filter(name__in=group_names)
    for a in AttachmentModel.objects.all():
        a.visible_by.set(default_groups)
    return


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("pia", "0039_intermediateevaluationmodel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="intermediateevaluationmodel",
            options={"ordering": ["date_evaluation"]},
        ),
        migrations.AddField(
            model_name="attachmentmodel",
            name="visible_by",
            field=models.ManyToManyField(to="auth.group"),
        ),
        migrations.RunPython(add_default_group),
    ]
