# Generated by Django 5.2.7 on 2025-10-02 10:26

from django.db import migrations, models
from django.contrib.auth.models import Group
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("pia", "0039_intermediateevaluationmodel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="intermediateevaluationmodel",
            options={"ordering": ["date_evaluation"]},
        ),
        migrations.AddField(
            model_name="attachmentmodel",
            name="visible_by",
            field=models.ManyToManyField(to="auth.group"),
        ),
    ]
