# Generated by Django 5.2.7 on 2025-10-03 07:12

from django.db import migrations
from django.contrib.auth.models import Group
from django.conf import settings


def add_default_group(apps, schema_editor):
    AttachmentModel = apps.get_model("pia", "AttachmentModel")
    group_names = [
        settings.DIRECTION_GROUP,
        settings.TEACHER_GROUP,
        settings.EDUCATOR_GROUP,
        settings.COORDONATOR_GROUP,
    ]
    default_groups = [g.id for g in Group.objects.filter(name__in=group_names)]
    for a in AttachmentModel.objects.all():
        a.visible_by.set(default_groups)
    return


class Migration(migrations.Migration):

    dependencies = [
        ("pia", "0040_alter_intermediateevaluationmodel_options_and_more"),
    ]

    operations = [
        migrations.RunPython(add_default_group),
    ]
