# Generated by Django 5.2.9 on 2025-12-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pia", "0041_auto_20251003_0912"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitysupportmodel",
            name="specific_support",
            field=models.TextField(blank=True, default=""),
        ),
    ]
