# Generated by Django 5.2.9 on 2025-12-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pia", "0042_activitysupportmodel_specific_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="branchgoalitemmodel",
            name="difficulties",
            field=models.ManyToManyField(blank=True, to="pia.resourcedifficultymodel"),
        ),
        migrations.AddField(
            model_name="branchgoalitemmodel",
            name="given_help",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="branchgoalitemmodel",
            name="indicator_action",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="crossgoalitemmodel",
            name="difficulties",
            field=models.ManyToManyField(blank=True, to="pia.resourcedifficultymodel"),
        ),
        migrations.AddField(
            model_name="crossgoalitemmodel",
            name="given_help",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="crossgoalitemmodel",
            name="indicator_action",
            field=models.TextField(blank=True),
        ),
    ]
