# Generated by Django 2.2.24 on 2021-09-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lateness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanctiontriggermodel',
            name='time_lateness_start',
            field=models.TimeField(blank=True, help_text="Début de l'interval du retard (facultatif).", null=True),
        ),
        migrations.AddField(
            model_name='sanctiontriggermodel',
            name='time_lateness_stop',
            field=models.TimeField(blank=True, help_text="Fin de l'interval du retard (facultatif si le début de l'interval n'est pas précisé).", null=True),
        ),
        migrations.AlterField(
            model_name='sanctiontriggermodel',
            name='next_week_day',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, 'Choisir un jour de la semaine'), (1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi'), (7, 'Même jour')], null=True),
        ),
    ]
