# Generated by Django 3.2.11 on 2022-02-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_courseschedulemodel_place"),
        ("lateness", "0002_auto_20210908_1407"),
    ]

    operations = [
        migrations.AddField(
            model_name="sanctiontriggermodel",
            name="classe",
            field=models.ManyToManyField(blank=True, to="core.ClasseModel"),
        ),
    ]
