# Generated by Django 4.2.16 on 2024-11-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lateness", "0004_alter_latenesssettingsmodel_printer"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailTemplateModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(default="warning", max_length=100)),
                ("template", models.TextField()),
            ],
        ),
    ]
