# Generated by Django 5.2.9 on 2026-01-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lateness", "0005_mailtemplatemodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="latenesssettingsmodel",
            name="use_email_school",
            field=models.BooleanField(default=False),
        ),
    ]
