# Generated by Django 5.2.15 on 2026-08-31 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lateness", "0006_latenesssettingsmodel_use_email_school"),
    ]

    operations = [
        migrations.AddField(
            model_name="latenessmodel",
            name="missing_card",
            field=models.BooleanField(default=False),
        ),
    ]
