# Generated by Django 5.2.15 on 2026-08-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lateness", "0007_latenessmodel_missing_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="latenesssettingsmodel",
            name="enable_missing_card",
            field=models.BooleanField(default=False),
        ),
    ]
