# Generated by Django 2.2.9 on 2020-02-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proeco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateSelectionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.TextField()),
            ],
        ),
    ]
