# Generated by Django 4.2.16 on 2025-01-20 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("proeco", "0003_overwritedatamodel_old_value_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProEcoWriteModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("app", models.CharField(max_length=20)),
                (
                    "method",
                    models.CharField(default="", max_length=30),
                ),
                ("payload", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[("waiting", "Waiting"), ("done", "Done"), ("error", "Error")],
                        default="waiting",
                        max_length=8,
                    ),
                ),
                (
                    "person",
                    models.CharField(
                        choices=[("stud", "Student"), ("resp", "Responsible")], max_length=4
                    ),
                ),
                ("datetime_creation", models.DateTimeField(auto_now_add=True)),
                ("datetime_update", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
