# Generated by Django 4.2.16 on 2025-01-23 08:40

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proeco", "0005_proecowritemodel_teaching_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proecowritemodel",
            name="app",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="proecowritemodel",
            name="payload",
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
